@startsalt
!include style.iuml
title Эскиз экрана «Регистрация обращения»
{+
  {* СПДО | Реестр обращений | Новое обращение | Статистика | Вход: Иванов И. (оператор) }
  ==
  { <b>Новое обращение
    Заголовок     | "Не открывается окно авторизации после обновления          "
    Категория     | ^Программное обеспечение^
    Компонент     | ^Клиентское приложение^
    Описание      | {SI
                    После обновления приложения при запуске появляется
                    белый экран вместо окна входа. Перезапуск не помогает.
                    .
                    .
                    }
    .             | { [Проверить и сохранить] | [Отмена] }
  }
  ==
  { <b>Похожие обращения (найдено 3)
    {#
      . | Заголовок | Сходство | Статус | Вид связи | Действие
      1 | Белый экран после обновления клиента | 0,91 | Решена | Дубликат | { [Дубликат] | [Открыть] }
      2 | Не работает форма входа | 0,78 | В работе | Связанное | { [Связать] | [Открыть] }
      3 | Ошибка обновления приложения | 0,64 | Решена | Связанное | { [Связать] | [Открыть] }
    }
    { [Создать как независимое обращение] | [Отклонить все рекомендации] }
  }
}
@endsalt
