skinparam defaultFontName "DejaVu Sans"
skinparam defaultFontSize 12
skinparam shadowing false
skinparam backgroundColor white
skinparam ArrowColor #333333
skinparam usecase {
  BackgroundColor #F7F7F7
  BorderColor #333333
}
skinparam actor {
  BackgroundColor #FFFFFF
  BorderColor #333333
}
skinparam activity {
  BackgroundColor #F7F7F7
  BorderColor #333333
  DiamondBackgroundColor #FFFFFF
  DiamondBorderColor #333333
}
skinparam class {
  BackgroundColor #FFFFFF
  BorderColor #333333
}
skinparam rectangle {
  BackgroundColor #FFFFFF
  BorderColor #999999
}
